[package]
name = "rpower"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.4"
home = "0.5.9"
iced = { version = "0.10.0", features = ["svg"] }
serde = "1.0.195"
thiserror = "1.0.56"
