# Required
width = 500
height = 100
background = [22, 22, 22]

commands = ["loginctl poweroff", "loginctl reboot", "loginctl suspend"]
icon_names          = ["poweroff", "reboot", "suspend", "lock"]
icon_colors         = [[85, 85, 85]]
normal_colors       = [[33, 33, 33]]
hover_colors        = [[60, 60, 60]]